apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2 # 초기 pod의 개수   
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: typing-backend:latest # server로 만든 docker 이미지  
        ports:
        - containerPort: 8000
