# kubernetes/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: typingking
spec:
  replicas: 2 # 초기 파드
  selector:
    matchLabels:
      app: typingking
      tier: backend
  template:
    metadata:
      labels:
        app: typingking
        tier: backend
    spec:
      containers:
        - name: client-backend
          image: chaeil22/client:latest
          ports:
            - containerPort: 9998
              name: backend
---
# kubernetes/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: typingking
spec:
  #type: LoadBalancer
  selector:
    app: typingking
    tier: backend
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 8080