apiVersion: v1
kind: Service
metadata:
  name: type-db
  labels:
    app: typingking  # 모든 거 이걸로 통일
spec:
  ports:
    - port: 3306
  selector:
    app: typingking
    tier: database
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-db-deployment
  labels:
    app: typingking
spec:
  selector:
    matchLabels:
      app: typingking
      tier: database
  template:
    metadata:
      labels:
        app: typingking
        tier: database
    spec:
      containers:
        - image: chaeil22/type-db:latest
          name: type-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "typeDB"
            - name: MYSQL_USER
              value: "cloud4"
            - name: MYSQL_PASSWORD
              value: "qwerty"
          ports:
            - containerPort: 3306
              name: database
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql  # 데이터가 저장되는 경로
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: typingking
spec:
  storageClassName: ""
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: typingking
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mysql/mysql_data
    type: DirectoryOrCreate